title: Time Switch
author: BaeJino
email: your@email

### https://[url][baseurl]

### if https://baealex.github.io/time-switch-jekyll-theme
url: https://baealex.github.io
baseurl: /time-switch/

### if https://baealex.github.io
# url: https://baealex.github.io
# baseurl: /

### use your utterances
utterances: baealex/utterances

plugins:
 - jekyll-feed
 - jekyll-seo-tag
