title:             BLEX
email:             im@baejino.com
description:       My Blog
author:            BLEX
baseurl:           "/HELLO-WORLD"
url:               "https://baealex.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   baealex
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
